#!/bin/bash

__git_ps1() {
    git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
}
PS1='[\[\e[1;32m\]\u\[\e[1;33m\]@\H \[\e[1;32m\]\s\[\033[1;31m\]$(__git_ps1 " (%s)") \[\e[1;35m\]\w\[\e[m\]]\[\e[1;36m\]\n\$\[\e[m\]'
